version: '3'
services:
  db:
    image: oscarfonts/h2
    container_name: kapusniak-database
    ports:
      - "1521:1521"
    environment:
      - H2_OPTIONS=-ifNotExists
      - DB_TYPE=h2
      - DB_NAME=testdb
      - DB_USER=sa
      - DB_PASSWORD=
    volumes:
      - ./webserver/src/main/resources/database/sql/:/opt/sql

  app:
    image: webserver
    build:
      context: ./webserver
    container_name: kapusniak-app
    ports:
      - "8080:8080"
    environment:
      - JDBC_URL=jdbc:h2:tcp://db:1521/testdb;INIT=runscript from '/opt/sql/ddl.sql'\;runscript from '/opt/sql/dml.sql'
      - JDBC_USER=sa
      - JDBC_PASSWORD=
    depends_on:
      - db

  client:
    image: maven:3.8.2-jdk-11
    container_name: kapusniak-test
    volumes:
      - ./webclient:/app
    command: mvn -f /app/pom.xml clean test
    depends_on:
      - app
